### ISSUE TITLE
Some editors don't work, except code editor

### ISSUE THREAD

**Issue by edgardozoppi** [gbdev/rgbds-live#30]
Taking a look to the source code it looks like it supports a graphic editor [js/gfx-editor.js](../tree/master/js/gfx-editor.js) for files with unknown extensions but it's not working for me.
Also I see that there is some kind of sound/music editor [tracker](../tree/master/tracker), but I don't know how to use it. I mean, how can users access to that feature from the home page?

**Comment by SelvinPL** [comment]
gfx-editor should be fixed with https://github.com/gbdev/rgbds-live/pull/35

**Comment by ISSOtm** [comment]
Since #35 has been merged, @edgardozoppi can you check again, please?

**Comment by edgardozoppi** [comment]
@ISSOtm so sorry for the late reply, I have the notifications disabled.

gfx-editor is working just fine now, but I still don't know how to use/access the sound/music editor [tracker](https://github.com/gbdev/rgbds-live/tree/master/tracker). Does anyone knows how?

**Comment by daid** [comment]
FYI: The tracker was a work in progress, I never finished it. Might be better to put it on some WIP branch and remove it from main.

**Comment by SelvinPL** [comment]
> FYI: The tracker was a work in progress, I never finished it. Might be better to put it on some WIP branch and remove it from main.

[I even make it working](http://selvin.pl/rgbds-live/tracker/) but i've lost commits (I belive it just requires older version of hUGEdriver/player)
